Repository Techeer-market/Frontend, pull requests merged in 2024-05, with the labels that each got.

#121 [refactor] 상품 목록 및 모달 리팩토링
  node_modules/.package-lock.json
  package-lock.json
  package.json
  src/assets/profile.png
  src/components/DropDown/index.tsx
  src/components/DropDown/styles.tsx
  src/components/EditInfoModal/ModalPortal.tsx
  src/components/EditInfoModal/index.tsx
  src/components/EditInfoModal/styles.tsx
  src/components/ProductForm/ProductForm.tsx
  src/components/ProductForm/index.tsx
  src/components/ProductForm/styles.tsx
  src/components/ProductForm/ui/IconLayout.tsx
  src/components/ProductForm/ui/Layout.tsx
  src/components/ProductForm/ui/TextInfo.tsx
  src/components/ProductForm/ui/Thumbnail.tsx
  src/hooks/useProductForm.ts
  src/hooks/useTokenRefreshTimer.ts
  src/main.tsx
  src/pages/EditInfo/index.tsx
  src/pages/EditInfo/styles.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/index.tsx
  src/pages/MyPage/styles.tsx
  src/pages/PurchaseList/index.tsx
  src/pages/SalesList/index.tsx
  src/pages/SalesList/styles.tsx
  src/pages/WishList/index.tsx
  src/queryClient.ts
  src/stories/BottomNavBar/BottomNavBar.stories.tsx
  src/stories/EditInfoModal/EditInfoModal.stories.tsx
  src/types/product.ts
Labels: 오류수정, 테스트, 리팩토링

#125 [fix] 메인페이지 글쓰기 버튼 UI 오른쪽 아래로 고정
  src/components/AddButton/index.tsx
  src/components/AddButton/styles.tsx
  src/components/Chat/index.tsx
  src/components/ChatContainer/styles.tsx
  src/components/ChatForm/style.tsx
  src/components/NavBar/styles.tsx
  src/components/ProductForm/styles.tsx
  src/pages/Main/index.tsx
  src/pages/Main/styles.tsx
Labels: UI디자인, 리팩토링

#122 fix: build시 에러나는 부분 수정
  src/components/ProductForm/ui/IconLayout.tsx
  src/pages/CategoryPage/index.tsx
  src/pages/SearchPage/index.tsx
  src/pages/SellerPage/index.tsx
  src/stories/ProductForm/index.tsx
Labels: 오류수정

#130 [feat]메인페이지 css 정리 , 작성페이지 기능 구현 및 css 정리 , 게시글 수정 페이지 이미지 수정 오류 해결
  node_modules/vite/bin/vite.js
  src/components/ProductForm/ui/TextInfo.tsx
  src/pages/ItemDetail/index.tsx
  src/pages/ItemUpadate/index.tsx
  src/pages/ItemUpadate/styles.tsx
  src/pages/Main/styles.tsx
  src/pages/WritePost/index.tsx
  src/pages/WritePost/styles.tsx
Labels: 오류수정, 기능구현, UI디자인, 리팩토링

#129 playwright 세팅 및 기능 수정 및 Storybook cd 적용
  .github/workflows/chromatic.yml
  .gitignore
  .storybook/preview.tsx
  node_modules/.package-lock.json
  package-lock.json
  package.json
  playwright.config.ts
  src/components/EditInfoModal/index.tsx
  src/components/EditInfoModal/styles.tsx
  src/components/TopNavBar/index.tsx
  src/hooks/useEditInfo.ts
  src/hooks/useFetchProductList.ts
  src/hooks/useTokenRefreshTimer.ts
  src/pages/EditInfo/index.tsx
  src/pages/LogIn/index.tsx
  src/pages/LogIn/styles.tsx
  src/stories/BottomNavBar/BottomNavBar.stories.tsx
  src/stories/BottomNavBar/index.tsx
  src/stories/EditInfoModal/EditInfoModal.stories.tsx
  src/stories/LoginPage/LoginPage.stories.tsx
  src/stories/ProductForm/ProductForm.stories.tsx
  src/stories/ProductForm/index.tsx
  src/stories/TopNavBar/TopNavBar.stories.tsx
  src/stories/TopNavBar/index.tsx
  tests-examples/demo-todo-app.spec.ts
  tests/example.spec.ts
Labels: 기능구현, 테스트, 환경설정
