Repository Techeer-market/Frontend, pull requests merged in 2024-01, with the labels that each got.

#92 fix: 불필요한 부분 수정
  src/App.tsx
  src/Router.tsx
  src/components/KakaoMap/index.tsx
  src/components/ProductForm/index.tsx
  src/constants/baseURL.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/SignUp/index.tsx
  src/queryClient.ts
  src/types/product.ts
  src/types/result.ts
Labels: 오류수정

#94 feat:작성 페이지 및 상세페이지 api 수정
  .gitignore
  node_modules/vite/bin/vite.js
  src/assets/uploadimg.svg
  src/hooks/useFetchProductList.ts
  src/mocks/api/data/itemDetailResultData.ts
Labels: 오류수정, 기능구현, 리팩토링

#95 feat: 상세페이지 , 작성페이지 api연동
  src/components/Carousel/index.tsx
  src/components/ProductForm/index.tsx
  src/pages/ItemDetail/index.tsx
  src/pages/ItemDetail/styles.tsx
  src/pages/WritePost/styles.tsx
Labels: 오류수정, 기능구현, UI디자인, 리팩토링

#100 fix: 메뉴바 아이콘 수정
  index.html
  src/Router.tsx
  src/assets/circle.svg
  src/components/ProductForm/index.tsx
  src/components/ProductForm/styles.tsx
Labels: 오류수정
